"""empty message

Revision ID: f471cba0baeb
Revises: ee195622fc23
Create Date: 2017-11-18 22:55:01.910767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f471cba0baeb'
down_revision = 'ee195622fc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('breweries', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breweries', 'date_modified')
    op.drop_column('breweries', 'date_created')
    # ### end Alembic commands ###
